'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'

interface Category {
  id: string
  name: string
  name_en?: string
  slug: string
  description?: string
  icon?: string
  priority: number
  parent_id?: string | null
  metadata?: Record<string, any>
  created_at: string
  updated_at: string
}

interface CategoryFormProps {
  /**
   * Initial category data for editing mode
   * If not provided, form is in create mode
   */
  initialCategory?: Category
  /**
   * All available categories for parent selection
   */
  allCategories: Category[]
  /**
   * Callback when form is submitted successfully
   */
  onSuccess?: (category: Category) => void
  /**
   * Locale for navigation
   */
  locale: string
}

/**
 * CategoryForm Component
 * 
 * Implements form for creating and editing categories with:
 * - Name, slug, description, parent category fields
 * - Slug auto-generation from name
 * - Slug format validation (kebab-case)
 * - Parent category dropdown with hierarchy
 * - Circular reference prevention
 * 
 * Requirements: 9.2, 9.3
 */
export default function CategoryForm({
  initialCategory,
  allCategories,
  onSuccess,
  locale,
}: CategoryFormProps) {
  const router = useRouter()
  const isEditMode = !!initialCategory

  // Form state
  const [formData, setFormData] = useState({
    name: initialCategory?.name || '',
    name_en: initialCategory?.name_en || '',
    slug: initialCategory?.slug || '',
    description: initialCategory?.description || '',
    icon: initialCategory?.icon || '📁',
    priority: initialCategory?.priority || 0,
    parent_id: initialCategory?.parent_id || null,
  })

  // UI state
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(!isEditMode)
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({})

  /**
   * Auto-generate slug from name when name changes
   * Only if slug hasn't been manually edited
   */
  useEffect(() => {
    if (slugAutoGenerated && formData.name) {
      const generatedSlug = formData.name
        .toLowerCase()
        .trim()
        .replace(/[^\w\s-]/g, '') // Remove special characters
        .replace(/\s+/g, '-') // Replace spaces with hyphens
        .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
        .replace(/^-+|-+$/g, '') // Remove leading/trailing hyphens

      setFormData((prev) => ({
        ...prev,
        slug: generatedSlug,
      }))
    }
  }, [formData.name, slugAutoGenerated])

  /**
   * Validate slug format (kebab-case)
   */
  const validateSlug = (slug: string): boolean => {
    const kebabCaseRegex = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
    return kebabCaseRegex.test(slug)
  }

  /**
   * Validate form data
   */
  const validateForm = (): boolean => {
    const errors: Record<string, string> = {}

    if (!formData.name.trim()) {
      errors.name = 'Category name is required'
    }

    if (!formData.slug.trim()) {
      errors.slug = 'Slug is required'
    } else if (!validateSlug(formData.slug)) {
      errors.slug = 'Slug must be in kebab-case format (lowercase letters, numbers, and hyphens only)'
    }

    // Check for circular reference
    if (formData.parent_id && initialCategory?.id === formData.parent_id) {
      errors.parent_id = 'A category cannot be its own parent'
    }

    // Check if parent is a descendant of current category (would create circular reference)
    if (isEditMode && formData.parent_id) {
      const isDescendant = isParentDescendant(initialCategory!.id, formData.parent_id)
      if (isDescendant) {
        errors.parent_id = 'Cannot set a descendant category as parent (would create circular reference)'
      }
    }

    setValidationErrors(errors)
    return Object.keys(errors).length === 0
  }

  /**
   * Check if a potential parent is a descendant of the current category
   */
  const isParentDescendant = (categoryId: string, potentialParentId: string): boolean => {
    const findDescendants = (id: string): string[] => {
      const children = allCategories.filter((c) => c.parent_id === id)
      const descendants = children.map((c) => c.id)
      children.forEach((child) => {
        descendants.push(...findDescendants(child.id))
      })
      return descendants
    }

    const descendants = findDescendants(categoryId)
    return descendants.includes(potentialParentId)
  }

  /**
   * Handle form submission
   */
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!validateForm()) {
      return
    }

    try {
      setLoading(true)
      setError(null)

      const url = isEditMode
        ? `/api/admin/categories/${initialCategory!.id}`
        : '/api/admin/categories'

      const method = isEditMode ? 'PUT' : 'POST'

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: formData.name.trim(),
          name_en: formData.name_en.trim() || undefined,
          slug: formData.slug.trim(),
          description: formData.description.trim() || undefined,
          icon: formData.icon || undefined,
          priority: formData.priority,
          parent_id: formData.parent_id || null,
        }),
      })

      if (!response.ok) {
        const errorData = await response.json()
        const errorMessage = errorData.error?.message || `Failed to ${isEditMode ? 'update' : 'create'} category`
        throw new Error(errorMessage)
      }

      const data = await response.json()
      const category = data.category

      // Call success callback if provided
      if (onSuccess) {
        onSuccess(category)
      }

      // Redirect to categories page
      router.push(`/${locale}/admin/categories`)
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'An error occurred'
      setError(errorMessage)
      console.error('Error submitting form:', err)
    } finally {
      setLoading(false)
    }
  }

  /**
   * Handle input change
   */
  const handleInputChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    const { name, value } = e.target

    if (name === 'slug') {
      // User is manually editing slug, so disable auto-generation
      setSlugAutoGenerated(false)
    }

    if (name === 'priority') {
      setFormData((prev) => ({
        ...prev,
        [name]: parseInt(value, 10),
      }))
    } else {
      setFormData((prev) => ({
        ...prev,
        [name]: value,
      }))
    }

    // Clear validation error for this field
    if (validationErrors[name]) {
      setValidationErrors((prev) => {
        const newErrors = { ...prev }
        delete newErrors[name]
        return newErrors
      })
    }
  }

  /**
   * Build hierarchical category list for parent selection
   */
  const buildCategoryOptions = (categories: Category[], level = 0, excludeId?: string) => {
    return categories
      .filter((c) => !excludeId || c.id !== excludeId)
      .sort((a, b) => (a.priority || 0) - (b.priority || 0))
      .map((category) => {
        const indent = '  '.repeat(level)
        const label = `${indent}${category.icon || '📁'} ${category.name}`

        return (
          <option key={category.id} value={category.id}>
            {label}
          </option>
        )
      })
  }

  /**
   * Get parent categories only (categories with no parent)
   */
  const getParentCategories = () => {
    return allCategories.filter((c) => !c.parent_id)
  }

  /**
   * Get all available parent options (excluding current category in edit mode)
   */
  const getAvailableParentOptions = () => {
    const parentCategories = getParentCategories()
    return buildCategoryOptions(parentCategories, 0, isEditMode ? initialCategory?.id : undefined)
  }

  return (
    <div className="max-w-2xl mx-auto">
      <form onSubmit={handleSubmit} className="bg-white rounded-lg shadow-sm p-8 space-y-6">
        {/* Header */}
        <div>
          <h2 className="text-2xl font-bold text-neutral-900">
            {isEditMode ? 'Edit Category' : 'Create New Category'}
          </h2>
          <p className="text-neutral-600 mt-1">
            {isEditMode
              ? 'Update category information and hierarchy'
              : 'Add a new category to organize your products'}
          </p>
        </div>

        {/* Error Message */}
        {error && (
          <div className="flex items-start gap-3 p-4 bg-red-50 border border-red-200 rounded-lg">
            <svg className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4v.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <div>
              <h3 className="font-semibold text-red-900">Error</h3>
              <p className="text-red-700 text-sm mt-1">{error}</p>
            </div>
          </div>
        )}

        {/* Category Name */}
        <div>
          <label htmlFor="name" className="block text-sm font-semibold text-neutral-900 mb-2">
            Category Name <span className="text-red-600">*</span>
          </label>
          <input
            type="text"
            id="name"
            name="name"
            value={formData.name}
            onChange={handleInputChange}
            placeholder="e.g., Hydraulic Systems"
            className={`w-full px-4 py-2 border rounded-lg font-medium transition-colors ${
              validationErrors.name
                ? 'border-red-300 bg-red-50 text-neutral-900 placeholder-red-300'
                : 'border-neutral-300 bg-white text-neutral-900 placeholder-neutral-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20'
            }`}
          />
          {validationErrors.name && (
            <p className="text-red-600 text-sm mt-1">{validationErrors.name}</p>
          )}
        </div>

        {/* English Name */}
        <div>
          <label htmlFor="name_en" className="block text-sm font-semibold text-neutral-900 mb-2">
            English Name <span className="text-neutral-400">(Optional)</span>
          </label>
          <input
            type="text"
            id="name_en"
            name="name_en"
            value={formData.name_en}
            onChange={handleInputChange}
            placeholder="e.g., Hydraulic Systems"
            className="w-full px-4 py-2 border border-neutral-300 rounded-lg font-medium bg-white text-neutral-900 placeholder-neutral-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 transition-colors"
          />
        </div>

        {/* Slug */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label htmlFor="slug" className="block text-sm font-semibold text-neutral-900">
              Slug <span className="text-red-600">*</span>
            </label>
            {slugAutoGenerated && (
              <span className="text-xs text-neutral-500 bg-neutral-100 px-2 py-1 rounded">
                Auto-generated
              </span>
            )}
          </div>
          <input
            type="text"
            id="slug"
            name="slug"
            value={formData.slug}
            onChange={handleInputChange}
            placeholder="e.g., hydraulic-systems"
            className={`w-full px-4 py-2 border rounded-lg font-mono text-sm transition-colors ${
              validationErrors.slug
                ? 'border-red-300 bg-red-50 text-neutral-900 placeholder-red-300'
                : 'border-neutral-300 bg-white text-neutral-900 placeholder-neutral-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20'
            }`}
          />
          <p className="text-neutral-500 text-xs mt-1">
            URL-friendly identifier in kebab-case (lowercase, hyphens only)
          </p>
          {validationErrors.slug && (
            <p className="text-red-600 text-sm mt-1">{validationErrors.slug}</p>
          )}
        </div>

        {/* Description */}
        <div>
          <label htmlFor="description" className="block text-sm font-semibold text-neutral-900 mb-2">
            Description <span className="text-neutral-400">(Optional)</span>
          </label>
          <textarea
            id="description"
            name="description"
            value={formData.description}
            onChange={handleInputChange}
            placeholder="Describe this category..."
            rows={4}
            className="w-full px-4 py-2 border border-neutral-300 rounded-lg bg-white text-neutral-900 placeholder-neutral-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 transition-colors resize-none"
          />
        </div>

        {/* Icon */}
        <div>
          <label htmlFor="icon" className="block text-sm font-semibold text-neutral-900 mb-2">
            Icon <span className="text-neutral-400">(Optional)</span>
          </label>
          <div className="flex gap-2">
            <input
              type="text"
              id="icon"
              name="icon"
              value={formData.icon}
              onChange={handleInputChange}
              placeholder="e.g., 📁"
              maxLength={2}
              className="flex-1 px-4 py-2 border border-neutral-300 rounded-lg bg-white text-neutral-900 placeholder-neutral-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 transition-colors"
            />
            <div className="flex items-center justify-center w-12 h-10 bg-neutral-100 rounded-lg text-2xl">
              {formData.icon || '📁'}
            </div>
          </div>
          <p className="text-neutral-500 text-xs mt-1">Single emoji or character</p>
        </div>

        {/* Parent Category */}
        <div>
          <label htmlFor="parent_id" className="block text-sm font-semibold text-neutral-900 mb-2">
            Parent Category <span className="text-neutral-400">(Optional)</span>
          </label>
          <select
            id="parent_id"
            name="parent_id"
            value={formData.parent_id || ''}
            onChange={handleInputChange}
            className={`w-full px-4 py-2 border rounded-lg bg-white text-neutral-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 transition-colors ${
              validationErrors.parent_id ? 'border-red-300 bg-red-50' : 'border-neutral-300'
            }`}
          >
            <option value="">No parent (top-level category)</option>
            {getAvailableParentOptions()}
          </select>
          {validationErrors.parent_id && (
            <p className="text-red-600 text-sm mt-1">{validationErrors.parent_id}</p>
          )}
          <p className="text-neutral-500 text-xs mt-1">
            Select a parent category to create a subcategory
          </p>
        </div>

        {/* Priority */}
        <div>
          <label htmlFor="priority" className="block text-sm font-semibold text-neutral-900 mb-2">
            Priority <span className="text-neutral-400">(Optional)</span>
          </label>
          <input
            type="number"
            id="priority"
            name="priority"
            value={formData.priority}
            onChange={handleInputChange}
            min="0"
            className="w-full px-4 py-2 border border-neutral-300 rounded-lg bg-white text-neutral-900 placeholder-neutral-400 focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 transition-colors"
          />
          <p className="text-neutral-500 text-xs mt-1">
            Lower numbers appear first in lists
          </p>
        </div>

        {/* Form Actions */}
        <div className="flex gap-3 pt-4 border-t border-neutral-200">
          <button
            type="submit"
            disabled={loading}
            className="flex-1 px-6 py-3 bg-primary-500 text-white rounded-lg font-semibold hover:bg-primary-600 disabled:bg-neutral-300 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
          >
            {loading && (
              <svg className="w-5 h-5 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
              </svg>
            )}
            {loading ? 'Saving...' : isEditMode ? 'Update Category' : 'Create Category'}
          </button>
          <button
            type="button"
            onClick={() => router.back()}
            className="px-6 py-3 border border-neutral-300 text-neutral-700 rounded-lg font-semibold hover:bg-neutral-50 transition-colors"
          >
            Cancel
          </button>
        </div>
      </form>
    </div>
  )
}
